services:
  cadastro-controladores-app-api:
    build: .
    ports:
      - "3000:3000"
    networks:
      minha-rede:
        aliases:
          - api 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

networks:
  minha-rede:
    external: true